name: Combine PowerShell Scripts for use with RMM

on:
  push:
    branches:
      - main

jobs:
  combine-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Combine PowerShell scripts
      shell: pwsh
      run: |
        $sourceDirectory = 'Public'
        $outputFilePath = 'EasyWarrantyCheck_RMM.ps1'
        
        $scriptFiles = Get-ChildItem -Path $sourceDirectory -Filter *.ps1 -Recurse
        
        $combinedContent = ''
        
        foreach ($file in $scriptFiles) {
            $fileContent = Get-Content $file.FullName -Raw
            $combinedContent += $fileContent + "`n`n"
        }
        
        # Add Get-Warranty function call at the end of the script
        $combinedContent += 'Get-Warranty`n'
        
        $combinedContent | Out-File -FilePath $outputFilePath -Force
        
        Write-Host "Combined script saved to: $outputFilePath"
        
        # Configure Git with the GitHub token
        & git config --local user.email "jayrodksmith@gmail.com"
        & git config --local user.name "jayrodksmith"
        git remote set-url origin "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"

        
        # Add, commit, and push changes
        git add $outputFilePath
        git commit -m "Combine PowerShell scripts"
        git push